language: cpp
script:
  - make && ./run
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.8
    - g++-4.8
    - clang
