language: cpp
script:
  - make clean; make && ./run
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libyajl-dev
    - libxml2-dev
    - clang
